from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional
import yaml


@dataclass
class EnvironmentSpec:
    """
    The universal artifact. Represents everything needed to reproduce a GPU environment.
    Generated by analyzer.py from a codebase, or loaded from .gpu-lol.yaml.
    Passed to skypilot.py to generate SkyPilot task YAML.
    """
    # Hardware
    gpu_type: Optional[str] = None       # "A40", "RTX4090", "H100" — None = let SkyPilot pick cheapest
    gpu_count: int = 1
    vram_required_gb: int = 16           # Minimum VRAM. Used to select GPU.

    # Software
    base_image: str = "runpod/pytorch:1.0.3-cu1290-torch291-ubuntu2204"
    python_version: str = "3.10"
    cuda_version: str = "12.1"

    # Dependencies
    requirements: list[str] = field(default_factory=list)   # pip packages
    system_packages: list[str] = field(default_factory=list)  # apt packages
    setup_commands: list[str] = field(default_factory=list)  # ordered shell commands

    # Asset symlinks: "remote_path:local_path" pairs created on the pod during setup
    # e.g. ["/workspace/huggingface:/root/.cache/huggingface"]
    # Generates: ln -sf /workspace/huggingface /root/.cache/huggingface
    asset_links: list[str] = field(default_factory=list)

    # Metadata
    name: str = "gpu-lol-env"
    workload_type: str = "interactive"   # "training", "inference", "interactive"
    created_from: str = "auto"
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> dict:
        """Serialize to dict for .gpu-lol.yaml"""
        return {
            "hardware": {
                "gpu_type": self.gpu_type,
                "gpu_count": self.gpu_count,
                "vram_required_gb": self.vram_required_gb,
            },
            "environment": {
                "base_image": self.base_image,
                "python_version": self.python_version,
                "cuda_version": self.cuda_version,
            },
            "dependencies": {
                "requirements": self.requirements,
                "system_packages": self.system_packages,
                "setup_commands": self.setup_commands,
                "asset_links": self.asset_links,
            },
            "meta": {
                "name": self.name,
                "workload_type": self.workload_type,
                "created_from": self.created_from,
                "created_at": self.created_at,
            }
        }

    def save(self, path: str = ".gpu-lol.yaml") -> str:
        """Save to .gpu-lol.yaml"""
        with open(path, "w") as f:
            yaml.dump(self.to_dict(), f, default_flow_style=False)
        return path

    @classmethod
    def from_dict(cls, data: dict) -> "EnvironmentSpec":
        """Load from .gpu-lol.yaml dict"""
        hw = data.get("hardware", {})
        env = data.get("environment", {})
        deps = data.get("dependencies", {})
        meta = data.get("meta", {})
        return cls(
            gpu_type=hw.get("gpu_type"),
            gpu_count=hw.get("gpu_count", 1),
            vram_required_gb=hw.get("vram_required_gb", 16),
            base_image=env.get("base_image", cls.__dataclass_fields__["base_image"].default),
            python_version=env.get("python_version", "3.10"),
            cuda_version=env.get("cuda_version", "12.1"),
            requirements=deps.get("requirements", []),
            system_packages=deps.get("system_packages", []),
            setup_commands=deps.get("setup_commands", []),
            asset_links=deps.get("asset_links", []),
            name=meta.get("name", "gpu-lol-env"),
            workload_type=meta.get("workload_type", "interactive"),
            created_from=meta.get("created_from", "file"),
            created_at=meta.get("created_at", datetime.now().isoformat()),
        )

    @classmethod
    def from_yaml_file(cls, path: str) -> "EnvironmentSpec":
        with open(path) as f:
            return cls.from_dict(yaml.safe_load(f))
